/* SPDX-License-Identifier: AGPL-3.0-only */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SNIPPETS = 'SNIPPETS';
export const NEW_SNIPPET = 'NEW_SNIPPET';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';
export const REMOVE_SNIPPET = 'REMOVE_SNIPPET';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CLEAR_CACHE = 'CLEAR_CACHE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const SET_COURSES = 'SET_COURSES';
export const SET_COURSES_PROMISE = 'SET_COURSES_PROMISE';
export const SET_SUBMISSIONS_PROMISE = 'SET_SUBMISSIONS_PROMISE';
export const SET_SUBMISSION_ASSIGNEE = 'SET_SUBMISSION_ASSIGNEE';
export const UPDATE_SUBMISSION = 'UPDATE_SUBMISSION';
export const ADD_SUBMISSION = 'ADD_SUBMISSION';
export const DELETE_SUBMISSION = 'DELETE_SUBMISSION';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const CLEAR_COURSES = 'CLEAR_COURSES';

export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';
export const UPDATE_CONTEXT_AMOUNT = 'UPDATE_CONTEXT_AMOUNT';

export const SET_PLAGIARISM_RUN = 'SET_PLAGIARISM_RUN';
export const ADD_PLAGIARISM_CASES = 'ADD_PLAGIARISM_CASES';
export const SET_PLAGIARISM_PROMISE = 'SET_PLAGIARISM_PROMISE';
export const CLEAR_PLAGIARISM_RUN = 'CLEAR_PLAGIARISM_RUN';
export const CLEAR_PLAGIARISM_RUNS = 'CLEAR_PLAGIARISM_RUNS';
