/* SPDX-License-Identifier: AGPL-3.0-only */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SNIPPETS = 'SNIPPETS';
export const NEW_SNIPPET = 'NEW_SNIPPET';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';
export const REMOVE_SNIPPET = 'REMOVE_SNIPPET';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CLEAR_CACHE = 'CLEAR_CACHE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const SET_COURSES = 'SET_COURSES';
export const SET_COURSES_PROMISE = 'SET_COURSES_PROMISE';
export const SET_SUBMISSIONS_PROMISE = 'SET_SUBMISSIONS_PROMISE';
export const SET_SUBMISSION_ASSIGNEE = 'SET_SUBMISSION_ASSIGNEE';
export const UPDATE_SUBMISSION = 'UPDATE_SUBMISSION';
export const ADD_SUBMISSION = 'ADD_SUBMISSION';
export const DELETE_SUBMISSION = 'DELETE_SUBMISSION';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const SET_ASSIGNMENT = 'SET_ASSIGNMENT';
export const CLEAR_COURSES = 'CLEAR_COURSES';

export const UPDATE_PREF = 'UPDATE_PREF';

export const SET_PLAGIARISM_RUN = 'SET_PLAGIARISM_RUN';
export const ADD_PLAGIARISM_CASES = 'ADD_PLAGIARISM_CASES';
export const SET_PLAGIARISM_PROMISE = 'SET_PLAGIARISM_PROMISE';
export const CLEAR_PLAGIARISM_RUN = 'CLEAR_PLAGIARISM_RUN';
export const CLEAR_PLAGIARISM_RUNS = 'CLEAR_PLAGIARISM_RUNS';

export const SET_AUTO_TEST = 'SET_AUTO_TEST';
export const DELETE_AUTO_TEST = 'DELETE_AUTO_TEST';
export const UPDATE_AUTO_TEST = 'UPDATE_AUTO_TEST';
export const UPDATE_AUTO_TEST_RUNS = 'UPDATE_AUTO_TEST_RUNS';
export const UPDATE_AUTO_TEST_SET = 'UPDATE_AUTO_TEST_SET';
export const DELETE_AUTO_TEST_SUITE = 'DELETE_AUTO_TEST_SUITE';
export const UPDATE_AUTO_TEST_RESULT = 'SET_AUTO_TEST_RESULT';
export const DELETE_AUTO_TEST_RESULT = 'DELETE_AUTO_TEST_RESULT';
export const SET_AUTO_TEST_RESULTS_BY_USER = 'SET_AUTO_TEST_RESULTS_BY_USER';
export const CLEAR_AUTO_TESTS = 'CLEAR_AUTO_TESTS';
export const CLEAR_AUTO_TEST_RUN = 'CLEAR_AUTO_TEST_RUN';

export const UPDATE_SUBMISSIONS = 'UPDATE_SUBMISSIONS';
export const ADD_SINGLE_SUBMISSION = 'ADD_SINGLE_SUBMISSION';
export const CLEAR_SUBMISSIONS = 'CLEAR_SUBMISSIONS';
export const SET_SINGLE_SUBMISSION_PROMISE = 'SET_SINGLE_SUBMISSION_PROMISE';
export const SET_SUBMISSIONS_BY_USER_PROMISE = 'SET_SUBMISSIONS_BY_USER_PROMISE';

export const UPDATE_LATEST_ACCESS = 'UPDATE_LATEST_ACCESS';
export const SET_CODE_CACHE = 'SET_CODE_CACHE';
export const CLEAR_CODE_CACHE = 'CLEAR_CODE_CACHE';

export const SET_RUBRIC = 'SET_RUBRIC';
export const CLEAR_RUBRIC = 'CLEAR_RUBRIC';
export const CLEAR_RUBRICS = 'CLEAR_RUBRICS';
export const SET_RUBRIC_RESULT = 'SET_RUBRIC_RESULT';
export const CLEAR_RUBRIC_RESULT = 'CLEAR_RUBRIC_RESULT';
export const CLEAR_RUBRIC_RESULTS = 'CLEAR_RUBRIC_RESULTS';

export const ADD_OR_UPDATE_USER = 'ADD_OR_UPDATE_USER';
export const UPDATE_GROUP_SET_PROMISE = 'UPDATE_GROUP_SET_PROMISE';
export const DELETE_GROUP_USER = 'DELETE_GROUP_USER';
export const CLEAR_USERS = 'CLEAR_USERS';

export const SET_FILETREE = 'SET_FILETREE';
export const DELETE_FILETREE = 'DELETE_FILETREE';
export const DELETE_ALL_FILETREES = 'DELETE_ALL_FILETREES';

export const SET_AT_FILETREE = 'SET_AT_FILETREE';

export const SET_WORKSPACE = 'SET_WORKSPACE';
export const CLEAR_ASSIGNMENT_WORKSPACES = 'CLEAR_ASSIGNMENT_WORKSPACES';
