/* SPDX-License-Identifier: AGPL-3.0-only */
export { default as Home } from './Home';
export { default as ManageCourse } from './ManageCourse';
export { default as ManageAssignment } from './ManageAssignment';
export { default as Submission } from './Submission';
export { default as Submissions } from './Submissions';
export { default as LTILaunch } from './LTILaunch';
export { default as ResetPassword } from './ResetPassword';
export { default as Admin } from './Admin';
export { default as Login } from './Login';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Register } from './Register';
export { default as Groups } from './Groups';
export { default as LoginAndRedirect } from './LoginAndRedirect';
export { default as UnsubscribePage } from './UnsubscribePage';
export { default as LTIProviderSetup } from './LTIProviderSetup';
export { default as AssignmentLogin } from './AssignmentLogin';
export { default as CourseEnroll } from './CourseEnroll';
export { default as SsoLogin } from './SsoLogin';
