"""Add amount_in_cool_off_period column

Revision ID: 027757394f6c
Revises: de68bd7d35bb
Create Date: 2020-01-13 17:47:00.569410

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '027757394f6c'
down_revision = 'de68bd7d35bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Assignment',
        sa.Column(
            'amount_in_cool_off_period',
            sa.Integer(),
            server_default='1',
            nullable=False
        )
    )
    op.create_check_constraint(
        "amount_in_cool_off_period_check",
        "Assignment",
        "amount_in_cool_off_period >= 1",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'amount_in_cool_off_period')
    op.drop_constraint(
        "amount_in_cool_off_period_check",
        "Assignment",
        type_='check',
    )
    # ### end Alembic commands ###
