"""Add reply comment types

Revision ID: 05fe57e91882
Revises: 853529060030bc48c81e
Create Date: 2020-03-23 22:31:22.540354

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '05fe57e91882'
down_revision = '853529060030bc48c81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('plain_text', 'markdown', name='commentreplytype')
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'comment_reply',
        sa.Column(
            'reply_type',
            enum,
            server_default='plain_text',
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_reply', 'reply_type')
    enum = ENUM(name='commentreplytype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
