"""Add columns for LTI 1.3 provider

Revision ID: 0a54c07d27ea
Revises: bef732f2f4ac
Create Date: 2020-02-04 13:06:27.799012

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '0a54c07d27ea'
down_revision = 'bef732f2f4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LTIProvider', sa.Column('auth_login_url', sa.Unicode(), nullable=True))
    op.add_column('LTIProvider', sa.Column('auth_token_url', sa.Unicode(), nullable=True))
    op.add_column('LTIProvider', sa.Column('client_id', sa.Unicode(), nullable=True))
    op.add_column('LTIProvider', sa.Column('crypto_key', sa.LargeBinary(), nullable=True))
    op.add_column('LTIProvider', sa.Column('key_set', sa.Unicode(), nullable=True))
    op.add_column('LTIProvider', sa.Column('key_set_url', sa.Unicode(), nullable=True))
    op.add_column('LTIProvider', sa.Column('lms_name', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'lms_name')
    op.drop_column('LTIProvider', 'key_set_url')
    op.drop_column('LTIProvider', 'key_set')
    op.drop_column('LTIProvider', 'crypto_key')
    op.drop_column('LTIProvider', 'client_id')
    op.drop_column('LTIProvider', 'auth_token_url')
    op.drop_column('LTIProvider', 'auth_login_url')
    # ### end Alembic commands ###
