"""Add ``available_at`` column for assignment

Revision ID: 0a97fb219970
Revises: 5f738a689495
Create Date: 2020-07-27 12:01:30.398055

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a97fb219970'
down_revision = '5f738a689495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'available_at')
    # ### end Alembic commands ###
