"""Add is_continuous_feedback_run column

Revision ID: 0e2fa74168cb
Revises: 3dc6f1de1017
Create Date: 2019-07-30 14:46:31.406956

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '0e2fa74168cb'
down_revision = '3dc6f1de1017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestRun', sa.Column('is_continuous_feedback_run', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestRun', 'is_continuous_feedback_run')
    # ### end Alembic commands ###
