"""Add auto_test_output_file table

Revision ID: 0ed7db5d0b70
Revises: 76c1a7c2f156f7a2d5aa
Create Date: 2019-11-13 14:36:52.250054

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '0ed7db5d0b70'
down_revision = '76c1a7c2f156f7a2d5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_test_output_file',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('filename', sa.Unicode(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('auto_test_result_id', sa.Integer(), nullable=True),
    sa.Column('auto_test_suite_id', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_test_result_id'], ['AutoTestResult.id'], ),
    sa.ForeignKeyConstraint(['auto_test_suite_id'], ['AutoTestSuite.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['auto_test_output_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_test_output_file')
    # ### end Alembic commands ###
