"""Add attachment_filename column

Revision ID: 10483a8dd3c8
Revises: 5fe9390d20fd
Create Date: 2020-06-19 10:58:45.524428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '10483a8dd3c8'
down_revision = '5fe9390d20fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_test_step_result', sa.Column('attachment_filename', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_test_step_result', 'attachment_filename')
    # ### end Alembic commands ###
