"""Add extra_info column to work

Revision ID: 159db3633c04
Revises: 8208ffd5c02b
Create Date: 2019-11-04 17:51:33.645116

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '159db3633c04'
down_revision = '8208ffd5c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Work', sa.Column('extra_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Work', 'extra_info')
    # ### end Alembic commands ###
