"""Add division_parent_id column

Revision ID: 193f394089dd
Revises: f2563a55410c7c6d3d38
Create Date: 2019-02-11 16:58:30.199707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193f394089dd'
down_revision = 'f2563a55410c7c6d3d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('division_parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Assignment', 'Assignment', ['division_parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_column('Assignment', 'division_parent_id')
    # ### end Alembic commands ###
