"""Add created_at column for PlagiarismRun

Revision ID: 19f00a8b1316
Revises: 5c3b448fc795
Create Date: 2018-09-12 15:26:44.477341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f00a8b1316'
down_revision = '5c3b448fc795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlagiarismRun', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('PlagiarismRun', 'json_config',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PlagiarismRun', 'json_config',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('PlagiarismRun', 'created_at')
    # ### end Alembic commands ###
