"""Modify GradeHistory table for AutoTest

Revision ID: 1dd5be4da723
Revises: d421dce68062
Create Date: 2019-05-20 12:18:29.992297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd5be4da723'
down_revision = 'd421dce68062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        bind = op.get_bind()
        has_size_type = bind.execute(
                "select exists (select 1 from pg_type "
                "where typname='gradeorigin')").scalar()
        if not has_size_type:
            op.execute("CREATE TYPE gradeorigin AS ENUM ('human', 'auto_test')")

    op.add_column('GradeHistory', sa.Column('grade_origin', sa.Enum('human', 'auto_test', name='gradeorigin'), server_default='human', nullable=False))
    op.create_check_constraint('grade_history_grade_origin_check', 'GradeHistory', "grade_origin != 'human' OR \"User_id\" IS NOT NULL")
    op.alter_column('GradeHistory', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GradeHistory', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('grade_history_grade_origin_check')
    op.drop_column('GradeHistory', 'grade_origin')
    # ### end Alembic commands ###
