"""Add explicit is_lti property on assignment model

Revision ID: 1e40c96db750
Revises: af3a4e88ca4c
Create Date: 2020-02-24 18:59:25.799323

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e40c96db750'
down_revision = 'af3a4e88ca4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Assignment', sa.Column('is_lti', sa.Boolean(), nullable=True)
    )
    bind = op.get_bind()
    bind.execute(
        """UPDATE "Assignment" set is_lti = (lti_assignment_id IS NOT NULL)"""
    )
    op.alter_column('Assignment', 'is_lti', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'is_lti')
    # ### end Alembic commands ###
