"""Add columns needed for plagiarism progress

Revision ID: 1edd7a1f8efc
Revises: 193f394089dd
Create Date: 2019-02-20 19:17:15.900565

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1edd7a1f8efc'
down_revision = '193f394089dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlagiarismRun', sa.Column('submissions_done', sa.Integer(), nullable=True))
    op.add_column('PlagiarismRun', sa.Column('submissions_total', sa.Integer(), nullable=True))
    op.execute('COMMIT')
    try:
        op.execute("ALTER TYPE plagiarismtate ADD VALUE 'comparing'")
        op.execute("ALTER TYPE plagiarismtate ADD VALUE 'starting'")
        op.execute("ALTER TYPE plagiarismtate ADD VALUE 'started'")
        op.execute("ALTER TYPE plagiarismtate ADD VALUE 'finalizing'")
        op.execute("ALTER TYPE plagiarismtate ADD VALUE 'parsing'")
    except:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PlagiarismRun', 'submissions_total')
    op.drop_column('PlagiarismRun', 'submissions_done')
    # ### end Alembic commands ###
