"""Add `network_disabled` field

Revision ID: 323e581d22cb
Revises: fc15ebd57afc
Create Date: 2019-05-28 13:34:04.776981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323e581d22cb'
down_revision = 'fc15ebd57afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestSuite', sa.Column('network_disabled', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestSuite', 'network_disabled')
    # ### end Alembic commands ###
