"""Remove unique constraint for LTIProvider.key

Revision ID: 36e4ca3d9214
Revises: 0d0ff8c58961
Create Date: 2020-05-09 15:09:54.561906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '36e4ca3d9214'
down_revision = '0d0ff8c58961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('LTIProvider_key_key', 'LTIProvider', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('LTIProvider_key_key', 'LTIProvider', ['key'])
    # ### end Alembic commands ###
