"""Remove base_systems column

Revision ID: 3d1a6f367ccc
Revises: b5518192aae730092065
Create Date: 2019-06-03 16:02:08.685536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d1a6f367ccc'
down_revision = 'b5518192aae730092065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTest', 'base_systems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTest', sa.Column('base_systems', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
