"""Add created_at fields

Revision ID: 450189fa482b
Revises: 91b33c886a97
Create Date: 2018-12-03 22:25:11.426184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450189fa482b'
down_revision = '91b33c886a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('GroupSet', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GroupSet', 'created_at')
    op.drop_column('Group', 'created_at')
    # ### end Alembic commands ###
