"""Add skipped state to taskresultstate

Revision ID: 5535cdc9389c
Revises: 860bf3135e0a23177739
Create Date: 2020-08-12 16:26:08.495213

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5535cdc9389c'
down_revision = '860bf3135e0a23177739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'taskresultstate', ['crashed', 'failed', 'finished', 'not_started', 'started'], ['crashed', 'failed', 'finished', 'not_started', 'skipped', 'started'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'taskresultstate', ['crashed', 'failed', 'finished', 'not_started', 'skipped', 'started'], ['crashed', 'failed', 'finished', 'not_started', 'started'])
    # ### end Alembic commands ###
