"""Add more options AutoTestRunState enum

Revision ID: 56cf69b5d451
Revises: 8ba2438c6c87
Create Date: 2019-05-23 15:36:08.568277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cf69b5d451'
down_revision = '8ba2438c6c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autotestrunstate', ['crashed', 'done', 'not_started', 'running', 'timed_out'], ['changing_runner', 'crashed', 'done', 'running', 'starting', 'timed_out', 'waiting_for_runner'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autotestrunstate', ['changing_runner', 'crashed', 'done', 'running', 'starting', 'timed_out', 'waiting_for_runner'], ['crashed', 'done', 'not_started', 'running', 'timed_out'])
    # ### end Alembic commands ###
