"""Add auto_approve column to peer feedback settings.

Revision ID: 5f738a689495
Revises: e5cac12d51d0
Create Date: 2020-07-17 16:49:56.668103

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f738a689495'
down_revision = 'e5cac12d51d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assignment_peer_feedback_settings',
        sa.Column(
            'auto_approved',
            sa.Boolean(),
            server_default='false',
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_peer_feedback_settings', 'auto_approved')
    # ### end Alembic commands ###
