"""Add junit_test step type

Revision ID: 5fe9390d20fd
Revises: 6dd3c8494722
Create Date: 2020-06-19 10:46:12.455825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '5fe9390d20fd'
down_revision = '6dd3c8494722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststeptesttype', ['check_points', 'custom_output', 'io_test', 'run_program'], ['check_points', 'custom_output', 'io_test', 'junit_test', 'run_program'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststeptesttype', ['check_points', 'custom_output', 'io_test', 'junit_test', 'run_program'], ['check_points', 'custom_output', 'io_test', 'run_program'])
    # ### end Alembic commands ###
