"""Add names to groups

Revision ID: 6125751db2df
Revises: 615667f99ae3
Create Date: 2018-11-12 15:03:56.473032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6125751db2df'
down_revision = '615667f99ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('name', sa.Unicode(), nullable=True))
    op.create_unique_constraint(None, 'Group', ['group_set_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Group', type_='unique')
    op.drop_column('Group', 'name')
    # ### end Alembic commands ###
