"""Add group tables

Revision ID: 615667f99ae3
Revises: d8252005c937
Create Date: 2018-11-10 14:54:26.638901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615667f99ae3'
down_revision = 'd8252005c937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('minimum_size', sa.Integer(), nullable=False),
    sa.Column('maximum_size', sa.Integer(), nullable=False),
    sa.CheckConstraint('minimum_size <= maximum_size'),
    sa.ForeignKeyConstraint(['assignment_id'], ['Assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_set_id', sa.Integer(), nullable=False),
    sa.Column('virtual_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_set_id'], ['GroupSet.id'], ),
    sa.ForeignKeyConstraint(['virtual_user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users-groups',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users-groups')
    op.drop_table('Group')
    op.drop_table('GroupSet')
    # ### end Alembic commands ###
