"""Add 'started_at' columns

Revision ID: 631bffa55c06
Revises: 3d1a6f367ccc
Create Date: 2019-06-04 15:19:52.401458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631bffa55c06'
down_revision = '3d1a6f367ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestResult', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('auto_test_step_result', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_test_step_result', 'started_at')
    op.drop_column('AutoTestResult', 'started_at')
    # ### end Alembic commands ###
