"""Add deleted column to file

Revision ID: 6337ebcfe414
Revises: b74373816ecc
Create Date: 2020-04-07 11:04:48.508715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6337ebcfe414'
down_revision = 'b74373816ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('File', 'deleted')
    # ### end Alembic commands ###
