"""Add hidden roles

Revision ID: 6e8744349b76
Revises: 2b1796c59c7d
Create Date: 2019-09-02 14:58:57.170795

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '6e8744349b76'
down_revision = '2b1796c59c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course_Role', sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course_Role', 'hidden')
    # ### end Alembic commands ###
