"""Added secret for editing lti providers

Revision ID: 73493f66f88d
Revises: 9adef0ecd40b
Create Date: 2020-05-15 11:10:29.123241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '73493f66f88d'
down_revision = '9adef0ecd40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LTIProvider', sa.Column('edit_secret', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'edit_secret')
    # ### end Alembic commands ###
