"""Remove unique contraint for lti_course_id

Revision ID: 764550f52c2f
Revises: 8746cca4f4b4
Create Date: 2020-06-16 14:49:20.921162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '764550f52c2f'
down_revision = '8746cca4f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_lti_provider_course_id_key', 'course_lti_provider', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_lti_provider_course_id_key', 'course_lti_provider', ['course_id'])
    # ### end Alembic commands ###
