"""Add ondelete='CASECADE' to file id references in PlagiarismMatch table

Revision ID: 77d138b081a4
Revises: 19f00a8b1316
Create Date: 2018-09-27 13:59:01.654704

SPDX-License-Identifier: AGPL-3.0-only
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d138b081a4'
down_revision = '19f00a8b1316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PlagiarismMatch_file2_id_fkey', 'PlagiarismMatch', type_='foreignkey')
    op.drop_constraint('PlagiarismMatch_file1_id_fkey', 'PlagiarismMatch', type_='foreignkey')
    op.create_foreign_key(None, 'PlagiarismMatch', 'File', ['file2_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'PlagiarismMatch', 'File', ['file1_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PlagiarismMatch', type_='foreignkey')
    op.drop_constraint(None, 'PlagiarismMatch', type_='foreignkey')
    op.create_foreign_key('PlagiarismMatch_file1_id_fkey', 'PlagiarismMatch', 'File', ['file1_id'], ['id'])
    op.create_foreign_key('PlagiarismMatch_file2_id_fkey', 'PlagiarismMatch', 'File', ['file2_id'], ['id'])
    # ### end Alembic commands ###
