"""Add `skipped` state to autoteststepresultstate

Revision ID: 78e54763e1d4
Revises: 6e8744349b76
Create Date: 2019-09-10 17:48:17.368405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e54763e1d4'
down_revision = '6e8744349b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststepresultstate', ['failed', 'not_started', 'passed', 'running', 'timed_out'], ['failed', 'not_started', 'passed', 'running', 'skipped', 'timed_out'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'autoteststepresultstate', ['failed', 'not_started', 'passed', 'running', 'skipped', 'timed_out'], ['failed', 'not_started', 'passed', 'running', 'timed_out'])
    # ### end Alembic commands ###
