"""Add run_setup_script

Revision ID: 7f18e98b7043
Revises: 323e581d22cb
Create Date: 2019-05-29 13:59:23.558096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f18e98b7043'
down_revision = '323e581d22cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTest', sa.Column('run_setup_script', sa.Unicode(), nullable=False, server_default="''"))
    op.add_column('AutoTestRun', sa.Column('setup_stderr', sa.Unicode(), nullable=True))
    op.add_column('AutoTestRun', sa.Column('setup_stdout', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestRun', 'setup_stdout')
    op.drop_column('AutoTestRun', 'setup_stderr')
    op.drop_column('AutoTest', 'run_setup_script')
    # ### end Alembic commands ###
