"""Add created_at and updated_at column to lti provider

Revision ID: 7f7c64ef9d84
Revises: c9e0f530b24b
Create Date: 2020-06-06 12:24:28.926292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '7f7c64ef9d84'
down_revision = 'c9e0f530b24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LTIProvider', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default='NOW()'))
    op.add_column('LTIProvider', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default='NOW()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'updated_at')
    op.drop_column('LTIProvider', 'created_at')
    # ### end Alembic commands ###
