"""Add finalized and intended_use column to lti provider

Revision ID: 7fb11708f03b
Revises: 36e4ca3d9214
Create Date: 2020-05-14 12:20:59.679226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '7fb11708f03b'
down_revision = '36e4ca3d9214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LTIProvider', sa.Column('finalized', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('LTIProvider', sa.Column('intended_use', sa.Unicode(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'finalized')
    op.drop_column('LTIProvider', 'intended_use')
    # ### end Alembic commands ###
