"""Add Sakai as LTI 1.3 provider

Revision ID: 801f35669a51
Revises: 6dd3c8494722
Create Date: 2020-06-16 17:06:09.667710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '801f35669a51'
down_revision = '6dd3c8494722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'lti1p3lmsnames', ['Blackboard', 'Brightspace', 'Canvas', 'Moodle'], ['Blackboard', 'Brightspace', 'Canvas', 'Moodle', 'Sakai'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'lti1p3lmsnames', ['Blackboard', 'Brightspace', 'Canvas', 'Moodle', 'Sakai'], ['Blackboard', 'Brightspace', 'Canvas', 'Moodle'])
    # ### end Alembic commands ###
