"""Add max_grade and lti_points_possible columns to assignment table

Revision ID: 8693e277a9ac
Revises: 729a1509580b
Create Date: 2018-09-22 01:05:31.904423

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '8693e277a9ac'
down_revision = '729a1509580b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Assignment',
        sa.Column('lti_points_possible', sa.Float(), nullable=True)
    )
    op.add_column(
        'Assignment', sa.Column('max_grade', sa.Float(), nullable=True)
    )
    conn = op.get_bind()
    conn.execute(
        text(
            """
    INSERT INTO "Permission" (name, default_value, course_permission)
    SELECT 'can_edit_maximum_grade', false, true WHERE NOT EXISTS
        (SELECT 1 FROM "Permission" WHERE name = 'can_edit_maximum_grade')
    """
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'max_grade')
    op.drop_column('Assignment', 'lti_points_possible')
    # ### end Alembic commands ###
