"""Add last_heartbeat column

Revision ID: 8ba2438c6c87
Revises: b9ef9242c18c
Create Date: 2019-05-23 11:30:11.396340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba2438c6c87'
down_revision = 'b9ef9242c18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestRunner', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestRunner', 'last_heartbeat')
    # ### end Alembic commands ###
