"""Add columns for linter log

Revision ID: 917f16d9303d
Revises: 193f394089dd
Create Date: 2019-02-21 22:20:07.754221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917f16d9303d'
down_revision = '193f394089dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LinterInstance', sa.Column('error_summary', sa.Unicode(), nullable=True))
    op.add_column('LinterInstance', sa.Column('stderr', sa.Unicode(), nullable=True))
    op.add_column('LinterInstance', sa.Column('stdout', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LinterInstance', 'stdout')
    op.drop_column('LinterInstance', 'stderr')
    op.drop_column('LinterInstance', 'error_summary')
    # ### end Alembic commands ###
