"""Add course id to group set

Revision ID: 91b33c886a97
Revises: ae7563fa356f
Create Date: 2018-12-01 14:09:13.761041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b33c886a97'
down_revision = 'ae7563fa356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GroupSet', sa.Column('Course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'GroupSet', 'Course', ['Course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'GroupSet', type_='foreignkey')
    op.drop_column('GroupSet', 'Course_id')
    # ### end Alembic commands ###
