"""Add proxy table

Revision ID: 9222d614d4bf
Revises: 027757394f6c
Create Date: 2020-01-19 23:58:21.665034

"""
from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '9222d614d4bf'
down_revision = '027757394f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('max_age', sa.Interval(), nullable=False),
    sa.Column('base_work_file_id', sa.Integer(), nullable=True),
    sa.Column('base_at_result_file_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('excluding_fileowner', ENUM('student', 'teacher', 'both', name='fileowner', create_type=False), nullable=True),
    sa.Column('allow_remote_resources', sa.Boolean(), nullable=False),
    sa.Column('allow_remote_scripts', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(base_at_result_file_id is NULL) != (base_work_file_id is NULL)', name='either_at_result_file_or_work_file'),
    sa.CheckConstraint('(base_at_result_file_id is NULL) or (excluding_fileowner is NULL)', name='fileowner_null_iff_work_file_id_null'),
    sa.CheckConstraint('allow_remote_resources or not allow_remote_scripts', name='remote_scripts_only_true_when_remote_resources_true'),
    sa.ForeignKeyConstraint(['base_at_result_file_id'], ['auto_test_output_file.id'], ),
    sa.ForeignKeyConstraint(['base_work_file_id'], ['File.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy')
    # ### end Alembic commands ###
