"""Make lms_name a enum

Revision ID: 9adef0ecd40b
Revises: 7fb11708f03b
Create Date: 2020-05-14 13:49:05.719660

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9adef0ecd40b'
down_revision = '7fb11708f03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        bind = op.get_bind()
        has_size_type = bind.execute(
                "select exists (select 1 from pg_type "
                "where typname='lti1p3lmsnames')").scalar()
        if not has_size_type:
            op.execute("CREATE TYPE lti1p3lmsnames AS ENUM ('Canvas', 'Blackboard', 'Moodle', 'Brightspace')")

    op.alter_column('LTIProvider', 'lms_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Canvas', 'Blackboard', 'Moodle', 'Brightspace', name='lti1p3lmsnames'),
                    existing_nullable=True,
                    postgresql_using='lms_name::lti1p3lmsnames'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LTIProvider', 'lms_name',
               existing_type=sa.Enum('Canvas', 'Blackboard', 'Moodle', 'Brightspace', name='ltip1_3lmsnames'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
