"""Add times_used attribute to proxy

Revision ID: a41953d99467
Revises: 182af783a7ee
Create Date: 2020-03-04 11:12:34.658267

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'a41953d99467'
down_revision = '182af783a7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('times_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'times_used')
    # ### end Alembic commands ###
