"""Add assignment_login_link table

Revision ID: a74d0e227051
Revises: 0a97fb219970
Create Date: 2020-07-28 15:18:40.666535

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a74d0e227051'
down_revision = '0a97fb219970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assignment_login_link',
        sa.Column(
            'id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('assignment_id', sa.Integer(), nullable=False),
        sa.Column('password', sqlalchemy_utils.PasswordType, nullable=True),
        sa.ForeignKeyConstraint(['assignment_id'], ['Assignment.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'Assignment',
        sa.Column(
            'send_login_links_token',
            sqlalchemy_utils.types.uuid.UUIDType(),
            nullable=True
        )
    )
    op.alter_column(
        'task_result', 'author_id', existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'task_result', 'author_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column('Assignment', 'send_login_links_token')
    op.drop_table('assignment_login_link')
    # ### end Alembic commands ###
