"""Add column to differentiate between lti version

Revision ID: a811d8ad8840
Revises: 9da3924d4ecc
Create Date: 2020-02-03 19:01:14.080006

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'a811d8ad8840'
down_revision = '9da3924d4ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    context = op.get_context()
    if context.bind.dialect.name == 'postgresql':
        bind = op.get_bind()
        has_size_type = bind.execute(
                "select exists (select 1 from pg_type "
                "where typname='ltiproviderversion')").scalar()
        if not has_size_type:
            op.execute("CREATE TYPE ltiproviderversion AS ENUM ('lti1.1', 'lti1.3')")
    op.add_column('LTIProvider', sa.Column('lti_provider_version', sa.Enum('lti1.1', 'lti1.3', name='ltiproviderversion'), server_default='lti1.1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'lti_provider_version')
    # ### end Alembic commands ###
