"""Switch child-parent relation on group_set - assignment

Revision ID: a9e2bd51371c
Revises: f615c74fe90f291d3ae6
Create Date: 2018-11-19 11:03:10.723491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e2bd51371c'
down_revision = 'f615c74fe90f291d3ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('group_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Assignment', 'GroupSet', ['group_set_id'], ['id'])
    op.drop_constraint('GroupSet_assignment_id_fkey', 'GroupSet', type_='foreignkey')
    op.drop_column('GroupSet', 'assignment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GroupSet', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('GroupSet_assignment_id_fkey', 'GroupSet', 'Assignment', ['assignment_id'], ['id'])
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_column('Assignment', 'group_set_id')
    # ### end Alembic commands ###
