"""Add more null checks

Revision ID: ae7563fa356f
Revises: 20830c609d28
Create Date: 2018-11-21 14:46:23.361118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7563fa356f'
down_revision = '20830c609d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PlagiarismRun', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PlagiarismRun', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
