"""Use ssh key per webhook, not per course

Revision ID: b5dca6f8efba
Revises: 159db3633c04
Create Date: 2019-11-05 15:43:34.576854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b5dca6f8efba'
down_revision = '159db3633c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course', 'ssh_username')
    op.drop_column('Course', 'ssh_key')
    op.add_column('webhook_base', sa.Column('ssh_key', sa.LargeBinary(), nullable=False))
    op.add_column('webhook_base', sa.Column('ssh_username', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_base', 'ssh_username')
    op.drop_column('webhook_base', 'ssh_key')
    op.add_column('Course', sa.Column('ssh_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('Course', sa.Column('ssh_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
