"""Add notification preferences table

Revision ID: b74373816ecc
Revises: dcaf540445e1
Create Date: 2020-03-27 16:51:51.042336

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'b74373816ecc'
down_revision = 'dcaf540445e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    notification_reason = ENUM(
        'assignee', 'author', 'replied', name='notification_reason'
    )

    op.create_table(
        'notifications_setting', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('reason', notification_reason, nullable=False),
        sa.Column(
            'value',
            sa.Enum(
                'daily',
                'direct',
                'off',
                'weekly',
                name='notification_setting_value'
            ),
            nullable=False
        ), sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'reason')
    )
    op.alter_column(
        'notification',
        'reasons',
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.ARRAY(
            notification_reason, as_tuple=True, dimensions=1
        ),
        existing_nullable=False,
        postgresql_using='reasons::notification_reason[]',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'notification',
        'reasons',
        existing_type=postgresql.ARRAY(
            sa.Enum(
                'assignee', 'author', 'replied', name='notification_reason'
            ),
            as_tuple=True,
            dimensions=1
        ),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False
    )
    op.drop_table('notifications_setting')
    # ### end Alembic commands ###
