"""Move foreign key AutoTestRun.runner_id to AutoTestRunner.run_id

Revision ID: b95df1528b32
Revises: 0e2fa74168cb
Create Date: 2019-08-20 16:12:29.348917

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b95df1528b32'
down_revision = '0e2fa74168cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestResult', sa.Column('auto_test_runner_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.create_foreign_key(None, 'AutoTestResult', 'AutoTestRunner', ['auto_test_runner_id'], ['id'])

    op.add_column('AutoTestRunner', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'AutoTestRunner', 'AutoTestRun', ['run_id'], ['id'])

    op.execute("""
    UPDATE "AutoTestRunner"
    SET run_id = (SELECT id from "AutoTestRun"
                  where runner_id = "AutoTestRunner".id);
    """)

    op.drop_constraint('AutoTestRun_runner_id_fkey', 'AutoTestRun', type_='foreignkey')
    op.drop_column('AutoTestRun', 'runner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AutoTestRunner', type_='foreignkey')
    op.drop_column('AutoTestRunner', 'run_id')
    op.add_column('AutoTestRun', sa.Column('runner_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('AutoTestRun_runner_id_fkey', 'AutoTestRun', 'AutoTestRunner', ['runner_id'], ['id'])
    op.drop_constraint(None, 'AutoTestResult', type_='foreignkey')
    op.drop_column('AutoTestResult', 'auto_test_runner_id')
    # ### end Alembic commands ###
