"""Add CourseSnippet table

Revision ID: bba485e5def7
Revises: 3a84e9b5fb45fddeac8b
Create Date: 2019-04-03 15:57:01.290788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba485e5def7'
down_revision = '3a84e9b5fb45fddeac8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CourseSnippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(), nullable=False),
    sa.Column('value', sa.Unicode(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CourseSnippet')
    # ### end Alembic commands ###
