"""Add non null checks on some columns

Revision ID: bcaac30cfecf
Revises: d8252005c937
Create Date: 2018-11-20 03:28:18.364990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaac30cfecf'
down_revision = 'd8252005c937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Assignment', 'Course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Comment', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Course_Role', 'Course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('File', 'Work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('GradeHistory', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('GradeHistory', 'Work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlagiarismCase', 'plagiarism_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlagiarismCase', 'work1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlagiarismCase', 'work2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlagiarismMatch', 'file1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PlagiarismMatch', 'file2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Work', 'Assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Work', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Work', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Work', 'Assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PlagiarismMatch', 'file2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PlagiarismMatch', 'file1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PlagiarismCase', 'work2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PlagiarismCase', 'work1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PlagiarismCase', 'plagiarism_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('GradeHistory', 'Work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('GradeHistory', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('File', 'Work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Course_Role', 'Course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Comment', 'User_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Assignment', 'Course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
