"""Improve speed AT run deletion

Revision ID: bdba5d2f6278
Revises: 35caaf04dbec
Create Date: 2020-01-20 17:13:27.315323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdba5d2f6278'
down_revision = '35caaf04dbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AutoTestStep_auto_test_suite_id_fkey', 'AutoTestStep', type_='foreignkey')
    op.create_foreign_key(None, 'AutoTestStep', 'AutoTestSuite', ['auto_test_suite_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('auto_test_step_result_auto_test_step_id_fkey', 'auto_test_step_result', type_='foreignkey')
    op.drop_constraint('auto_test_step_result_auto_test_result_id_fkey', 'auto_test_step_result', type_='foreignkey')
    op.create_foreign_key(None, 'auto_test_step_result', 'AutoTestResult', ['auto_test_result_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'auto_test_step_result', 'AutoTestStep', ['auto_test_step_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auto_test_step_result', type_='foreignkey')
    op.drop_constraint(None, 'auto_test_step_result', type_='foreignkey')
    op.create_foreign_key('auto_test_step_result_auto_test_result_id_fkey', 'auto_test_step_result', 'AutoTestResult', ['auto_test_result_id'], ['id'])
    op.create_foreign_key('auto_test_step_result_auto_test_step_id_fkey', 'auto_test_step_result', 'AutoTestStep', ['auto_test_step_id'], ['id'])
    op.drop_constraint(None, 'AutoTestStep', type_='foreignkey')
    op.create_foreign_key('AutoTestStep_auto_test_suite_id_fkey', 'AutoTestStep', 'AutoTestSuite', ['auto_test_suite_id'], ['id'])
    # ### end Alembic commands ###
