"""Add auth audience column on lti provider

Revision ID: c9e0f530b24b
Revises: 97234ea957585a44f5f1
Create Date: 2020-05-29 15:36:47.608743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'c9e0f530b24b'
down_revision = '97234ea957585a44f5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LTIProvider', sa.Column('auth_audience', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LTIProvider', 'auth_audience')
    # ### end Alembic commands ###
