"""Add more AutoTest columns

Revision ID: d421dce68062
Revises: 559f0c415cd9
Create Date: 2019-05-13 15:20:55.714360

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd421dce68062'
down_revision = '559f0c415cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AutoTestRunner',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('simple_runner', native_enum=False), nullable=False),
    sa.Column('ipaddr', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('AutoTestRun', sa.Column('kill_date', sa.DateTime(), nullable=True))
    op.add_column('AutoTestRun', sa.Column('runner_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.add_column('AutoTestRun', sa.Column('started_date', sa.DateTime(), nullable=True))
    op.add_column('AutoTestRun', sa.Column('state', sa.Enum('not_started', 'running', 'done', 'timed_out', name='autotestrunstate', native_enum=False), nullable=False))
    op.create_foreign_key(None, 'AutoTestRun', 'AutoTestRunner', ['runner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AutoTestRun', type_='foreignkey')
    op.drop_column('AutoTestRun', 'state')
    op.drop_column('AutoTestRun', 'started_date')
    op.drop_column('AutoTestRun', 'runner_id')
    op.drop_column('AutoTestRun', 'kill_date')
    op.drop_table('AutoTestRunner')
    # ### end Alembic commands ###
