"""Add submission_info column to AutoTestSuite

Revision ID: d9de662a4ec9
Revises: f6fc95ece26a
Create Date: 2020-06-04 11:26:33.495441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'd9de662a4ec9'
down_revision = 'f6fc95ece26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestSuite', sa.Column('submission_info', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestSuite', 'submission_info')
    # ### end Alembic commands ###
