"""Add columns for broker

Revision ID: da1fef325fc6
Revises: 92d8eea8c48e
Create Date: 2019-06-11 21:07:22.479925

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'da1fef325fc6'
down_revision = '92d8eea8c48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestRun', sa.Column('job_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    op.add_column('AutoTestRun', sa.Column('job_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestRun', 'job_number')
    op.drop_column('AutoTestRun', 'job_id')
    # ### end Alembic commands ###
