"""Add AnalyticsWorkspace model

Revision ID: da889c40b2a7
Revises: 94b1a38179a5
Create Date: 2020-03-19 10:56:10.540723

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.sql import text
from sqlalchemy.dialects import postgresql

import cg_dt_utils

# revision identifiers, used by Alembic.
revision = 'da889c40b2a7'
down_revision = '94b1a38179a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'analytics_workspace', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('assignment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['assignment_id'], ['Assignment.id'],
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    conn = op.get_bind()
    for assig_id, in conn.execute(text('SELECT id from "Assignment"')):
        now = cg_dt_utils.DatetimeWithTimezone.utcnow()
        conn.execute(
            text(
                """
        INSERT INTO analytics_workspace
                (created_at, updated_at, assignment_id)
                VALUES
                (:now, :now, :assig_id)
                """,
            ),
            now=now,
            assig_id=assig_id,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analtics_workspace')
    # ### end Alembic commands ###
