"""Add AutoTestSuite.command_time_limit

Revision ID: de751ecfe976
Revises: 631bffa55c06
Create Date: 2019-06-05 10:51:37.939422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de751ecfe976'
down_revision = '631bffa55c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestSuite', sa.Column('command_time_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AutoTestSuite', 'command_time_limit')
    # ### end Alembic commands ###
