"""Add check constraint that ensures that reviewer and subject are different

Revision ID: e5cac12d51d0
Revises: 25521e40a00f
Create Date: 2020-07-16 15:27:56.526060

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5cac12d51d0'
down_revision = '25521e40a00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('peer_feedback_reviewer_is_not_subject', 'assignment_peer_feedback_connection', 'peer_user_id != user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('peer_feedback_reviewer_is_not_subject')
    # ### end Alembic commands ###
