"""Add upload types options to Assignment table

Revision ID: f0e58d3d989b
Revises: c9e2479be1b8
Create Date: 2019-11-05 18:01:19.352821

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f0e58d3d989b'
down_revision = 'c9e2479be1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('files_upload_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('Assignment', sa.Column('webhook_upload_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.create_check_constraint("upload_methods_check", "Assignment", "files_upload_enabled or webhook_upload_enabled")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'webhook_upload_enabled')
    op.drop_column('Assignment', 'files_upload_enabled')
    op.drop_constraint("upload_methods_check", "Assignment", type_="check")
    # ### end Alembic commands ###
