"""Remote useless after_run column and add job_id to runner

Revision ID: f9a29920788a
Revises: da1fef325fc6
Create Date: 2019-06-12 14:49:27.384203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f9a29920788a'
down_revision = 'da1fef325fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestRunner', sa.Column('job_id', sa.Unicode(), nullable=True))
    op.drop_column('AutoTestRunner', 'after_run')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AutoTestRunner', sa.Column('after_run', postgresql.ENUM('not_called', 'calling', 'called', name='autotestafterrunstate'), server_default=sa.text("'called'::autotestafterrunstate"), autoincrement=False, nullable=False))
    op.drop_column('AutoTestRunner', 'job_id')
    # ### end Alembic commands ###
