#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-only

res="127"

echo "Running test with pwd: $(pwd)"

set -o xtrace

case "$TO_RUN" in
    "backend-tests")
        SQLALCHEMY_DATABASE_URI='postgresql:///travis_ci_test' ./manage.py db upgrade

        pytest --cov psef \
               --postgresql=travis_ci_test \
               --cov-report term-missing \
               "$(pwd)/psef_test" \
               -vvvv
        res1="$?"

        make doctest
        res2="$?"

        res=$(( res1 + res2 ))

        set +o xtrace
        ;;
    "lint")
        make pylint
        res1="$?"

        make privacy_statement
        [[ -z "$NO_INSTALL" ]] && npm install
        npm run lint
        res2="$?"

        make mypy
        res3="$?"

        out="$(make isort_check)"
        res4=$?
        if [[ "$res4" -ne 0 ]]; then
            echo "$out"
        fi

        make yapf_check
        res5=$?

        out="$(npm run check-format)"
        res6=$?
        if [[ "$res6" -ne 0 ]]; then
            echo "$out"
        fi

        res=$(( res1 + res2 + res3 + res4 + res5 + res6 ))
        set +x xtrace
        ;;
    "js_unit")
        make privacy_statement
        [[ -z "$NO_INSTALL" ]] && npm install
        npm run unit
        res="$?"
        set +x xtrace
        ;;

esac

set +o xtrace

exit "$res"
