"""Add index to state columns for broker

Revision ID: 5203c1c439bb
Revises: b017a6d1d244
Create Date: 2020-03-25 13:30:53.139011

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5203c1c439bb'
down_revision = 'b017a6d1d244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_state'), 'job', ['state'], unique=False)
    op.create_index(op.f('ix_runner_state'), 'runner', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runner_state'), table_name='runner')
    op.drop_index(op.f('ix_job_state'), table_name='job')
    # ### end Alembic commands ###
