"""Initial version db

Revision ID: 977953e3aefd
Revises:
Create Date: 2019-06-11 21:04:58.183115

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '977953e3aefd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'job', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'waiting_for_runner', 'started', 'finished', name='jobstate'
            ),
            nullable=False
        ), sa.Column('remote_id', sa.Unicode(), nullable=False),
        sa.Column('cg_url', sa.Unicode(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_job_remote_id'), 'job', ['remote_id'], unique=True
    )
    op.create_table(
        'runner',
        sa.Column(
            'id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False
        ), sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('ipaddr', sa.Unicode(), nullable=True),
        sa.Column(
            'type',
            sa.Enum('aws', 'transip', 'dev_runner', name='runnertype'),
            nullable=False
        ),
        sa.Column(
            'state',
            sa.Enum(
                'not_running',
                'running',
                'cleaning',
                'cleaned',
                name='runnerstate'
            ),
            nullable=False
        ), sa.Column('instance_id', sa.Unicode(), nullable=True),
        sa.Column('last_log_emitted', sa.Boolean(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['job_id'],
            ['job.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_runner_ipaddr'), 'runner', ['ipaddr'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runner_ipaddr'), table_name='runner')
    op.drop_table('runner')
    op.drop_index(op.f('ix_job_remote_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
