"""Add unique index on job_id

Revision ID: a0afa010403e
Revises: 4188b4e91a76
Create Date: 2019-06-16 00:24:55.057489

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a0afa010403e'
down_revision = '4188b4e91a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'runner', ['job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runner', type_='unique')
    # ### end Alembic commands ###
