"""Add started_at column

Revision ID: b5db0fe05ae7
Revises: 16d3300cd15b
Create Date: 2019-09-11 12:47:34.015325

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5db0fe05ae7'
down_revision = '16d3300cd15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'runner', sa.Column('started_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runner', 'started_at')
    # ### end Alembic commands ###
