"""Add wantend_runners key

Revision ID: f8b56bf0ce3b
Revises: a0afa010403e
Create Date: 2019-08-17 14:30:55.473770

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8b56bf0ce3b'
down_revision = 'a0afa010403e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'job',
        sa.Column(
            'wanted_runners', sa.Integer(), server_default='1', nullable=False
        )
    )
    op.drop_constraint('runner_job_id_key', 'runner', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('runner_job_id_key', 'runner', ['job_id'])
    op.drop_column('job', 'wanted_runners')
    # ### end Alembic commands ###
